### ISSUE TITLE
Inconsistent spaces in css

### ISSUE THREAD

**Issue by veredrec** [FACN3/project_mrrobot#36]
e.g https://github.com/FACN3/project_mrrobot/blob/master/style.css#L38 
vs.
https://github.com/FACN3/project_mrrobot/blob/master/style.css#L46

Or in a different way - 
https://github.com/FACN3/project_mrrobot/blob/master/style.css#L56
vs. 
https://github.com/FACN3/project_mrrobot/blob/master/style.css#L72

**Comment by prodionov** [comment]
@veredrec the issue if fixed with Atom Content Beautify

**Comment by veredrec** [comment]
@prodionov great!
